DISTRICT_INDICES = {
    "Allan Hancock Joint Community College District": 0,
    "Antelope Valley Community College District": 1,
    "Barstow Community College District": 2,
    "Butte-Glenn Community College District": 3,
    "Cabrillo Community College District": 4,
    "Cerritos Community College District": 5,
    "Chabot-Las Positas Community College District": 6,
    "Chaffey Community College District": 7,
    "Citrus Community College District": 8,
    "Coast Community College District": 9,
    "Compton Community College District": 10,
    "Contra Costa Community College District": 11,
    "Copper Mountain Community College District": 12,
    "Desert Community College District": 13,
    "El Camino Community College District": 14,
    "Feather River Community College District": 15,
    "Foothill-De Anza Community College District": 16,
    "Gavilan Community College District": 17,
    "Glendale Community College District": 18,
    "Grossmont-Cuyamaca Community College District": 19,
    "Hartnell Community College District": 20,
    "Imperial Community College District": 21,
    "Kern Community College District": 22,
    "Lake Tahoe Community College District": 23,
    "Lassen Community College District": 24,
    "Long Beach Community College District": 25,
    "Los Angeles Community College District": 26,
    "Los Rios Community College District": 27,
    "Marin Community College District": 28,
    "Mendocino-Lake Community College District": 29,
    "Merced Community College District": 30,
    "MiraCosta Community College District": 31,
    "Monterey Peninsula Community College District": 32,
    "Mt. San Antonio Community College District": 33,
    "Mt. San Jacinto Community College District": 34,
    "Napa Valley Community College District": 35,
    "North Orange County Community College District": 36,
    "Ohlone Community College District": 37,
    "Palo Verde Community College District": 38,
    "Palomar Community College District": 39,
    "Pasadena Area Community College District": 40,
    "Peralta Community College District": 41,
    "Rancho Santiago Community College District": 42,
    "Redwoods Community College District": 43,
    "Rio Hondo Community College District": 44,
    "Riverside Community College District": 45,
    "San Bernardino Community College District": 46,
    "San Diego Community College District": 47,
    "San Francisco Community College District": 48,
    "San Joaquin Delta Community College District": 49,
    "San Jose-Evergreen Community College District": 50,
    "San Luis Obispo County Community College District": 51,
    "San Mateo County Community College District": 52,
    "Santa Barbara Community College District": 53,
    "Santa Clarita Community College District": 54,
    "Santa Monica Community College District": 55,
    "Sequoias Community College District": 56,
    "Shasta-Tehama-Trinity Joint Community College District": 57,
    "Sierra Joint Community College District": 58,
    "Siskiyou Joint Community College District": 59,
    "Solano Community College District": 60,
    "Sonoma County Junior College District": 61,
    "South Orange County Community College District": 62,
    "Southwestern Community College District": 63,
    "State Center Community College District": 64,
    "Ventura County Community College District": 65,
    "Victor Valley Community College District": 66,
    "West Hills Community College District": 67,
    "West Kern Community College District": 68,
    "West Valley-Mission Community College District": 69,
    "Yosemite Community College District": 70,
    "Yuba Community College District": 71
}
