from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path

from tests.golden.runner import load_scenarios, run_scenario


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "bootstrap_golden_scenario"


class BootstrapGoldenScriptTests(unittest.TestCase):
    def test_bootstrap_creates_valid_scenario_and_expected(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            request_path = tmp_path / "request.json"
            scenarios_dir = tmp_path / "scenarios"
            expected_dir = tmp_path / "expected"

            request_payload = {
                "college_id": "de_anza",
                "target_ucs": ["UCSD", "UCLA"],
                "ge_pattern": "IGETC",
                "completed_courses": ["MATH 1A"],
            }
            request_path.write_text(json.dumps(request_payload), encoding="utf-8")

            cmd = [
                str(SCRIPT),
                "--id",
                "bootstrap_sample",
                "--request-file",
                str(request_path),
                "--description",
                "generated by test",
                "--scenarios-dir",
                str(scenarios_dir),
                "--expected-dir",
                str(expected_dir),
            ]
            subprocess.run(cmd, check=True, cwd=str(REPO_ROOT))

            scenario_files = list(scenarios_dir.glob("*.json"))
            expected_files = list(expected_dir.glob("*.json"))
            self.assertEqual(len(scenario_files), 1)
            self.assertEqual(len(expected_files), 1)

            loaded = load_scenarios(scenarios_dir)
            self.assertEqual(len(loaded), 1)
            canonical = run_scenario(loaded[0], expected_dir)
            self.assertEqual(canonical.get("version"), "v1")


if __name__ == "__main__":
    unittest.main()

